 const CardPhotos = {
    "The Magician":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-magician.jpg",
    "The Fool":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-fool.jpg",
    "The High Priestess":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-highpriestess.jpg",
    "The Empress":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-empress.jpg",
    "The Emperor":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-emperor.jpg",
    "The Hierophant":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-hierophant.jpg",
    "The Lovers":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-lovers.jpg",
    "The Chariot":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-chariot.jpg",
    "Fortitude":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-strength.jpg",
    "The Hermit":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-hermit.jpg",
    "Wheel Of Fortune":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-wheeloffortune.jpg",
    "Justice":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-justice.jpg",
    "The Hanged Man":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-hangedman.jpg",
    "Death":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-death.jpg",
    "Temperance":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-temperance.jpg",
    "The Devil":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-devil.jpg",
    "The Tower":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-tower.jpg",
    "The Star":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-star.jpg",
    "The Moon":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-moon.jpg",
    "The Sun":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-sun.jpg",
    "The Last Judgment":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-judgement.jpg",
    "The World":"https://www.tarotcardmeanings.net/images/tarotcards/tarot-world.jpg",
    "Ace of Wands":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-wands-01.jpg",
    "Two of Wands":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-wands-02.jpg",
    "Three of Wands":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-wands-03.jpg",
    "Four of Wands":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-wands-04.jpg",
    "Five of Wands":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-wands-05.jpg",
    "Six of Wands":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-wands-06.jpg",
    "Seven of Wands":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-wands-07.jpg",
    "Eight of Wands":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-wands-08.jpg",
    "Nine of Wands":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-wands-09.jpg",
    "Ten of Wands":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-wands-10.jpg",
    "Page of Wands":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-wands-11.jpg",
    "Knight of Wands":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-wands-12.jpg",
    "Queen of Wands":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-wands-13.jpg",
    "King of Wands":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-wands-14.jpg",
    "Ace of Pentacles":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-pentacles-01.jpg",
    "Two of Pentacles":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-pentacles-02.jpg",
    "Three of Pentacles":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-pentacles-03.jpg",
    "Four of Pentacles":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-pentacles-04.jpg",
    "Five of Pentacles":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-pentacles-05.jpg",
    "Six of Pentacles":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-pentacles-06.jpg",
    "Seven of Pentacles":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-pentacles-07.jpg",
    "Eight of Pentacles":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-pentacles-08.jpg",
    "Nine of Pentacles":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-pentacles-09.jpg",
    "Ten of Pentacles":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-pentacles-10.jpg",
    "Page of Pentacles":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-pentacles-11.jpg",
    "Knight of Pentacles":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-pentacles-12.jpg",
    "Queen of Pentacles":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-pentacles-13.jpg",
    "King of Pentacles":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-pentacles-14.jpg",
    "Ace of Cups":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-cups-01.jpg",
    "Two of Cups":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-cups-02.jpg",
    "Three of Cups":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-cups-03.jpg",
    "Four of Cups":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-cups-04.jpg",
    "Five of Cups":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-cups-05.jpg",
    "Six of Cups":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-cups-06.jpg",
    "Seven of Cups":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-cups-07.jpg",
    "Eight of Cups":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-cups-08.jpg",
    "Nine of Cups":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-cups-09.jpg",
    "Ten of Cups":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-cups-10.jpg",
    "Knight of Cups":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-cups-12.jpg",
    "Queen of Cups":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-cups-13.jpg",
    "Page of Cups":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-cups-11.jpg",
    "King of Cups":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-cups-14.jpg",
    "Ace of Swords":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-swords-01.jpg",
    "Two of Swords":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-swords-02.jpg",
    "Three of Swords":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-swords-03.jpg",
    "Four of Swords":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-swords-04.jpg",
    "Five of Swords":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-swords-05.jpg",
    "Six of Swords":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-swords-06.jpg",
    "Seven of Swords":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-swords-07.jpg",
    "Eight of Swords":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-swords-08.jpg",
    "Nine of Swords":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-swords-09.jpg",
    "Ten of Swords":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-swords-10.jpg",
    "Page of Swords":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-swords-11.jpg",
    "Knight of Swords":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-swords-12.jpg",
    "King of Swords":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-swords-13.jpg",
    "Queen of Swords":"https://www.tarotcardmeanings.net/images/tarotcards-large/tarot-swords-14.jpg",


 }

 export default CardPhotos;